# Time-reversed Diffusion Sampler (DIS)
name: dds
step_size: ${target.dds.step_size}
batch_size: ${target.all.batch_size}
iters: 40000
init_std: ${target.dds.initial_scale}
num_steps: 128
loss: "elbo"  # Currently only supports 'elbo'
grad_clip: 1.
noise_scale: 6.
max_diffusion: 6.  # Note: this is not used in the algorithm

defaults:
  - model: pisgrad_net
  - noise_schedule: cosine  # Note: this is not used in the algorithm; TODO: make DDS noise schedule configurable

model:
  use_lp: True
  num_hid: 64
  bias_init: 0.  # Initialization of the last layers' bias of the time-dependent network
  weight_init: 1e-8  # Initialization of the last layers' weights of the time-dependent network
