# Time-reversed Diffusion Sampler (DIS)
name: dds
step_size: ${target.dds.step_size}
batch_size: ${target.all.batch_size}
iters: 40000
init_std: ${target.dds.init_std}
num_steps: 128
loss: "elbo"  # Currently only supports 'elbo'
grad_clip: 1.
noise_scale: ${target.dds.noise_scale}

defaults:
  - model: pisgrad_net

model:
  use_lp: True
  num_hid: 64
  bias_init: 0.  # Initialization of the last layers' bias of the time-dependent network
  weight_init: 1e-8  # Initialization of the last layers' weights of the time-dependent network
