name: gaussian_mixture40
num_components: 40
dim: 2
has_entropy: True

fn:
  _target_: targets.gmm40.GMM40
  num_components: ${target.num_components}
  dim: ${target.dim}
  log_Z: 0.
  can_sample: True
  sample_bounds: None
  loc_scaling: 40
  scale_scaling: 1

# Experiment-specific algorithm parameters
# ----------------------------------------

mfvi: # Gaussian Mean Field Variational Inference
  initial_scale: 40.
  step_size: 1e-2

gmmvi: # Gaussian Mixture Model Variational Inference
  initial_scale: 40.

nfvi: # Normalizing Flow Variational Inference
  initial_scale: 40.
  step_size: 1e-3

hmc:  # Hamilton Monte Carlo
  hmc_step_size: [0.2, 0.2]

smc: # Sequential Monte Carlo Sampler
  initial_scale: 40.

smc_advanced:
  initial_scale: 40.
  target_ess: 0.99
  hmc_step_size: [0.01, 0.001]

flow_transport: # Flow Transport Methods (AFT/CRAFT)
  initial_scale: 40.
  step_size: 1e-4

fab: # Flow Annealed Importance Sampling Bootstrap
  initial_scale: 40.
  step_size: 1e-4

ud_langevin:  # Underdamped Langevin Methods (UHA/LDVI)
  max_diffusion: 1.
  initial_scale: 1.
  step_size: 5e-4

od_langevin:  # Overdamped Langevin Methods (ULA/MCD)
  max_diffusion: 1.
  initial_scale: 1.
  step_size: 5e-4

cmcd:  # Controlled Monte Carlo Diffusions
  max_diffusion: 10.
  initial_scale: 40.
  step_size: 5e-4

scld:
  max_diffusion: 20.
  initial_scale: 40.
  step_size: 1e-3
  annealing_step_size: 1e-3
  n_sub_traj: 4

pis: # Path Integral Sampler
  max_diffusion: 40.
  step_size: 5e-4

dis: # Time-reversed Diffusion Sampler
  max_diffusion: 10.
  initial_scale: 40.
  step_size: 5e-4

dds: # Denoising Diffusion Sampler
  noise_scale: 10.
  initial_scale: 40.
  step_size: 5e-4

gbs:  # General Bridge Sampler
  max_diffusion: 10.
  initial_scale: 40.
  step_size: 5e-4

gfn_tb: # Trajectory Balance
  reference_process: pinned_brownian  # ou or pinned_brownian
  initial_scale: 10.  # only used if reference_process is ou
  max_diffusion: 10.
  step_size: 1e-3
  logZ_step_size: 5e-2
  init_logZ: 0.

gfn_subtb: # Sub-Trajectory Balance
  reference_process: pinned_brownian  # ou or pinned_brownian
  initial_scale: 10.  # only used if reference_process is ou
  max_diffusion: 10.
  step_size: 1e-3
  logflow_step_size: 1e-2

all: # Parameters that are shared between all algorithms
  batch_size: 2000
