name: nice_digits
dim: 196 # 196 or 784
has_entropy: True

fn:
  _target_: targets.nice.NiceTarget
  dataset: mnist
  dim: ${target.dim}
  log_Z: 0.
  can_sample: True
  sample_bounds: None

# Experiment-specific algorithm parameters
# ----------------------------------------

mfvi: # Gaussian Mean Field Variational Inference
  init_std: 5.
  step_size: 1e-3

gmmvi: # Gaussian Mixture Model Variational Inference
  init_std: 5.

nfvi: # Normalizing Flow Variational Inference
  init_std: 5.
  step_size: 1e-3

hmc:  # Hamilton Monte Carlo
  hmc_step_size: [0.2, 0.2]

smc: # Sequential Monte Carlo Sampler
  init_std: 5.

flow_transport: # Flow Transport Methods (AFT/CRAFT)
  init_std: 5.
  step_size: 1e-3

fab: # Flow Annealed Importance Sampling Bootstrap
  init_std: 5.
  step_size: 1e-4

ud_langevin:  # Underdamped Langevin Methods (UHA/LDVI)
  init_std: 5.
  step_size: 5e-4
  eps: 1e-2

od_langevin:  # Overdamped Langevin Methods (ULA/MCD/CMCD)
  max_diffusion: 10.
  init_std: 5.
  step_size: 5e-4

cmcd:  # Controlled Monte Carlo Diffusions
  max_diffusion: 10.
  init_std: 5.
  step_size: 5e-4

pis: # Path Integral Sampler
  max_diffusion: 5.
  step_size: 5e-4

dis: # Time-reversed Diffusion Sampler
  init_std: 5.
  step_size: 5e-4

dds: # Denoising Diffusion Sampler
  init_std: 5.
  step_size: 5e-4

gfn_tb: # Generative Flow Networks
  max_diffusion: 5.
  step_size: 5e-4

gfn_subtb: # Sub-Trajectory Balance
  reference_process: ou_dds  # pinned_brownian, ou, or ou_dds
  init_std: 5.  # for ou or ou_dds
  max_diffusion: 5.  # for pinned_brownian or ou
  n_chunks: 32
  step_size: 1e-4
  logflow_step_size: 1e-4
  beta_step_size: 1e-2
  logZ_step_size: 1e-2  # for ou or ou_dds
  init_logZ: 0.  # for ou or ou_dds
  mcmc_step_size: 0.2

gbs:  # General Bridge Sampler
  max_diffusion: 10.
  init_std: .1
  step_size: 1e-3

all: # Parameters that are shared between all algorithms
  batch_size: 2000
  iters: 40000
  milestones: [20000, 30000]
  num_steps: 128
  use_lp: True
  num_hid: 64