name: sonar
dim: 61
has_entropy: False

fn:
  _target_: targets.sonar.Sonar
  log_Z:
  can_sample: False
  sample_bounds: None

# Experiment-specific algorithm parameters
# ----------------------------------------

mfvi: # Gaussian Mean Field Variational Inference
  init_std: 0.1
  step_size: 1e-3

gmmvi: # Gaussian Mixture Model Variational Inference
  init_std: 1.

hmc:  # Hamilton Monte Carlo
  hmc_step_size: [0.05, 0.001]

smc: # Sequential Monte Carlo Sampler
  init_std: 1.

smc_advanced:
  init_std: 1.
  target_ess: 0.99
  hmc_step_size: [0.05, 0.01]

flow_transport: # Flow Transport Methods (AFT/CRAFT)
  init_std: 1.
  step_size: 1e-3

fab: # Flow Annealed Importance Sampling Bootstrap
  init_std:  0.1
  step_size: 1e-3

ud_langevin:  # Underdamped Langevin Methods (UHA/LDVI)
  max_diffusion: 1.
  init_std: 1.
  step_size: 1e-3

od_langevin:  # Overdamped Langevin Methods (ULA/MCD/CMCD)
  max_diffusion: 1.
  init_std: .1
  step_size: 1e-3

cmcd:  # Controlled Monte Carlo Diffusions
  max_diffusion: 1.
  init_std: .1
  step_size: 1e-3

scld:
  init_std: 1.
  max_diffusion: 1.
  step_size: 1e-3
  annealing_step_size: 1e-2
  n_sub_traj: 128

pis: # Path Integral Sampler
  max_diffusion: 1.
  step_size: 1e-3

dis: # Time-reversed Diffusion Sampler
  init_std: 1.
  step_size: 5e-4

dds: # Denoising Diffusion Sampler
  init_std: 1.
  step_size: 1e-3

gfn_tb: # Generative Flow Networks
  max_diffusion: 1.
  step_size: 1e-3

gbs:  # General Bridge Sampler
  max_diffusion: 10.
  init_std: .1
  step_size: 1e-3

all: # Parameters that are shared between all algorithms
  batch_size: 2000
