name: student_t_mixture

num_components: 10
dim: 50
has_entropy: True

fn:
  _target_: targets.student_t_mixture.StudentTMixtureModel
  num_components: ${target.num_components}
  dim: ${target.dim}
  log_Z: 0.
  can_sample: True
  sample_bounds: None

# Experiment-specific algorithm parameters
# !!! Default Parameters; Currently not tuned for this experiment !!!
# ----------------------------------------

mfvi: # Gaussian Mean Field Variational Inference
  init_std: 15.
  step_size: 1e-3

gmmvi: # Gaussian Mixture Model Variational Inference
  init_std: 15.

nfvi: # Normalizing Flow Variational Inference
  init_std: 15.
  step_size: 1e-3

hmc:  # Hamilton Monte Carlo
  hmc_step_size: [0.1, 0.1]

smc: # Sequential Monte Carlo Sampler
  init_std: 15.

smc_advanced:
  init_std: 15.
  target_ess: 0.99
  hmc_step_size: [0.1, 0.2]

flow_transport: # Flow Transport Methods (AFT/CRAFT)
  init_std: 15.
  step_size: 1e-3

fab: # Flow Annealed Importance Sampling Bootstrap
  init_std: 15.
  step_size: 5e-4

ud_langevin:  # Underdamped Langevin Methods (UHA/LDVI)
  max_diffusion: 1.
  init_std: 15.
  step_size: 5e-4

od_langevin:  # Overdamped Langevin Methods (ULA/MCD)
  max_diffusion: 1.
  init_std: 15.
  step_size: 5e-4

cmcd:  # Controlled Monte Carlo Diffusions
  max_diffusion: 1.
  init_std: 15.
  step_size: 5e-4

dis: # Time-reversed Diffusion Sampler
  init_std: 15.
  step_size: 5e-4

############# HYPERPARAMETERS USED IN OUR PAPER #############
# These can be slightly different from the original settings

dds: # Denoising Diffusion Sampler
  init_std: 15.
  step_size: 1e-4

pis: # Path Integral Sampler
  max_diffusion: 15.
  step_size: 1e-4

gfn_tb: # Trajectory Balance
  reference_process: ou_dds  # pinned_brownian, ou, or ou_dds
  init_std: 15.  # for ou or ou_dss
  max_diffusion: 15.  # for pinned_brownian or ou
  step_size: 1e-3
  logZ_step_size: 1e-1
  init_logZ: 0.

gfn_subtb: # Sub-Trajectory Balance
  reference_process: ou_dds  # pinned_brownian, ou, or ou_dds
  init_std: 15.  # for ou or ou_dds
  max_diffusion: 15.  # for pinned_brownian or ou
  n_chunks: 32
  step_size: 1e-3
  logflow_step_size: 1e-3
  beta_step_size: 1e-1
  logZ_step_size: 1e-1  # for ou or ou_dds
  init_logZ: 0.  # for ou or ou_dds
  mcmc_step_size: 0.2
  flow_num_hid: 256

all: # Parameters that are shared between all algorithms
  batch_size: 2000
  iters: 40000
  milestones: [20000, 30000]
  num_steps: 128
  use_lp: True
  num_hid: 64